[package]
name = "sqip_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
eyre = "0.6.12"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
tokio = { version = "1.38.1", features = ["full"] }
