const SQUARE_APP_ID = process.env.EXPO_PUBLIC_SQUARE_APP_ID
const SQUARE_LOCATION_ID = process.env.EXPO_PUBLIC_SQUARE_LOCATION_ID
// Make sure to remove trailing `/` since the CHARGE_SERVER_URL puts it
const CHARGE_SERVER_HOST = process.env.EXPO_PUBLIC_CHARGE_SERVER_HOST
const CHARGE_SERVER_URL = `${CHARGE_SERVER_HOST}/chargeForCookie`
const GOOGLE_PAY_LOCATION_ID = process.env.EXPO_PUBLIC_SQUARE_LOCATION_ID
const APPLE_PAY_MERCHANT_ID = process.env.EXPO_PUBLIC_APPLE_PAY_MERCHANT_ID

module.exports = {
  SQUARE_APP_ID,
  SQUARE_LOCATION_ID,
  CHARGE_SERVER_HOST,
  CHARGE_SERVER_URL,
  GOOGLE_PAY_LOCATION_ID,
  APPLE_PAY_MERCHANT_ID
}
